### ISSUE TITLE
Compilation errors trying to build the app 

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Android#63]
Hi, I'm new to OVMS android. I have a bit of experience using Android Studio for other Android projects. I'm struggling to get started with OVSM android due to java compiler errors. I would like to work on #61 

I'm running Android Studio 3.1.4. Can other devs successfully build the app in its current form? Am I missing any setup steps? Any ideas how I can try and debug this?  

```
org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:207)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:133)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:59)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:128)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:46)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:314)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:204)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:134)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:109)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:62)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:69)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:30)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

![screenshot_2018-08-08_23-52-30](https://user-images.githubusercontent.com/758844/43868582-2c4dd47a-9b66-11e8-982c-0d83be106263.png)

**Comment by glynhudson** [comment]
Update: looks like the message output provides some more clues. Some resources seem to be missing:

```
Executing tasks: [:OpenVehicleApp:assembleDebug]

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
:OpenVehicleApp:buildInfoDebugLoader
:LuttuLibrary:preBuild UP-TO-DATE
:LuttuLibrary:preDebugBuild UP-TO-DATE
:LuttuLibrary:compileDebugAidl UP-TO-DATE
:LuttuLibrary:compileDebugRenderscript UP-TO-DATE
:LuttuLibrary:checkDebugManifest UP-TO-DATE
:LuttuLibrary:generateDebugBuildConfig UP-TO-DATE
:LuttuLibrary:generateDebugResValues UP-TO-DATE
:LuttuLibrary:generateDebugResources UP-TO-DATE
:LuttuLibrary:packageDebugResources UP-TO-DATE
:LuttuLibrary:platformAttrExtractor UP-TO-DATE
:LuttuLibrary:processDebugManifest UP-TO-DATE
:LuttuLibrary:generateDebugRFile UP-TO-DATE
:LuttuLibrary:prepareLintJar UP-TO-DATE
:LuttuLibrary:generateDebugSources UP-TO-DATE
:LuttuLibrary:javaPreCompileDebug
Note: /media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/LuttuLibrary/src/main/java/com/luttu/CameraCall.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:LuttuLibrary:compileDebugJavaWithJavac
:LuttuLibrary:processDebugJavaRes NO-SOURCE
:LuttuLibrary:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
:OpenVehicleApp:preBuild UP-TO-DATE
:OpenVehicleApp:preDebugBuild UP-TO-DATE
:OpenVehicleApp:compileDebugAidl UP-TO-DATE
:LuttuLibrary:packageDebugRenderscript NO-SOURCE
:OpenVehicleApp:compileDebugRenderscript UP-TO-DATE
:OpenVehicleApp:checkDebugManifest UP-TO-DATE
:OpenVehicleApp:generateDebugBuildConfig UP-TO-DATE
:OpenVehicleApp:prepareLintJar UP-TO-DATE
:OpenVehicleApp:mainApkListPersistenceDebug UP-TO-DATE
:OpenVehicleApp:generateDebugResValues UP-TO-DATE
:OpenVehicleApp:generateDebugResources UP-TO-DATE
:OpenVehicleApp:processDebugGoogleServices
:OpenVehicleApp:mergeDebugResources UP-TO-DATE
:OpenVehicleApp:createDebugCompatibleScreenManifests UP-TO-DATE
:OpenVehicleApp:processDebugManifest
:OpenVehicleApp:splitsDiscoveryTaskDebug UP-TO-DATE
:OpenVehicleApp:processDebugResources
:OpenVehicleApp:generateDebugSources
:OpenVehicleApp:javaPreCompileDebug
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/witdet/ReversedSeekBar.java:7: error: cannot find symbol
import android.support.v7.widget.AppCompatSeekBar;
                                ^
  symbol:   class AppCompatSeekBar
  location: package android.support.v7.widget
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/witdet/ReversedSeekBar.java:9: error: cannot find symbol
public class ReversedSeekBar extends AppCompatSeekBar {
                                     ^
  symbol: class AppCompatSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:148: error: incompatible types: View cannot be converted to ReversedSeekBar
		ReversedSeekBar bar = (ReversedSeekBar) findViewById(R.id.tabInfoSliderChargerControl);
		                                                    ^
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:149: error: cannot find symbol
		bar.setOnSeekBarChangeListener(new OnSeekBarChangeListener() {
		   ^
  symbol:   method setOnSeekBarChangeListener(<anonymous OnSeekBarChangeListener>)
  location: variable bar of type ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:558: error: incompatible types: View cannot be converted to ReversedSeekBar
		ReversedSeekBar bar = (ReversedSeekBar) findViewById(R.id.tabInfoSliderChargerControl);
		                                                    ^
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:569: error: cannot find symbol
			bar.setVisibility(View.INVISIBLE);
			   ^
  symbol:   method setVisibility(int)
  location: variable bar of type ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:585: error: cannot find symbol
				bar.setVisibility(View.INVISIBLE);
				   ^
  symbol:   method setVisibility(int)
  location: variable bar of type ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:623: error: cannot find symbol
				bar.setVisibility(View.VISIBLE);
				   ^
  symbol:   method setVisibility(int)
  location: variable bar of type ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:636: error: cannot find symbol
						bar.setProgress(100);
						   ^
  symbol:   method setProgress(int)
  location: variable bar of type ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:644: error: cannot find symbol
						bar.setProgress(100);
						   ^
  symbol:   method setProgress(int)
  location: variable bar of type ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:656: error: cannot find symbol
						bar.setProgress(0);
						   ^
  symbol:   method setProgress(int)
  location: variable bar of type ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/InfoFragment.java:669: error: cannot find symbol
						bar.setProgress(100);
						   ^
  symbol:   method setProgress(int)
  location: variable bar of type ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/witdet/ReversedSeekBar.java:18: error: cannot find symbol
			paramCanvas.scale(-1.0F, 1.0F, getWidth() / 2.0F, getHeight() / 2.0F);
			                               ^
  symbol:   method getWidth()
  location: class ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/witdet/ReversedSeekBar.java:18: error: cannot find symbol
			paramCanvas.scale(-1.0F, 1.0F, getWidth() / 2.0F, getHeight() / 2.0F);
			                                                  ^
  symbol:   method getHeight()
  location: class ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/witdet/ReversedSeekBar.java:21: error: cannot find symbol
			super.onDraw(paramCanvas);
			^
  symbol:   variable super
  location: class ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/witdet/ReversedSeekBar.java:29: error: cannot find symbol
			paramMotionEvent.setLocation(getWidth() - paramMotionEvent.getX(),
			                             ^
  symbol:   method getWidth()
  location: class ReversedSeekBar
/media/chrx/2C6DBC5732C3E088/android-dev/Open-Vehicle-Android/OpenVehicleApp/src/main/java/com/openvehicles/OVMS/ui/witdet/ReversedSeekBar.java:32: error: cannot find symbol
		return super.onTouchEvent(paramMotionEvent);
		       ^
  symbol:   variable super
  location: class ReversedSeekBar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
17 errors
:OpenVehicleApp:compileDebugJavaWithJavac FAILED
:OpenVehicleApp:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':OpenVehicleApp:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by glynhudson** [comment]
Ok I've fixed it, PR submitted https://github.com/openvehicles/Open-Vehicle-Android/pull/64
